CREATE TABLE bowler (
id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
password VARCHAR(100) NOT NULL
);

CREATE TABLE field (
fid INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
bid INT(6) UNSIGNED,
fielders VARCHAR(100) NOT NULL,
FOREIGN KEY (bid) REFERENCES bowler(id)
);